import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src"])
env.Append(CPPDEFINES=["WINDOWS_ENABLED"])
env.Append(LIBS=["user32", "shell32", "gdi32", "ole32", "uuid", "wintrust", "crypt32"])

sources = [
    "src/register_types.cpp",
    "src/lmm_native_bridge.cpp",
    "src/tray_controller.cpp",
    "src/window_controller.cpp",
]

target = "bin/win64/letsmakemoney_native"
library = env.SharedLibrary(target=target, source=sources)

Default(library)
